# ================================
# 1. Base
# ================================
FROM node:24-bookworm-slim AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable

WORKDIR /app


# ================================
# 2. Build
# ================================
FROM base AS build

COPY . .

RUN pnpm install --frozen-lockfile

RUN pnpm --filter @sigip/shared build

RUN pnpm --filter backend build


# ================================
# 3. Producción
# ================================
FROM base AS production

ENV NODE_ENV=production

COPY --from=build /app /app

RUN chown -R node:node /app

USER node

EXPOSE 3000

CMD ["pnpm", "--filter", "backend", "start:prod"]