export const incidentTypesSeed = [
  {
    code: 'DIA_ECONOMICO',
    name: 'Día económico',
    description: 'Autoriza día económico marcado en el formato.',
    temporalMode: 'SINGLE_DATE',
    appointmentScope: 'BASE',
    isActive: true,
    sortOrder: 10,
  },
  {
    code: 'JUSTIFICACION_ENTRADA',
    name: 'Justificación de entrada',
    description: 'Justifica entradas en las fechas indicadas.',
    temporalMode: 'SINGLE_DATE',
    appointmentScope: 'ALL',
    isActive: true,
    sortOrder: 20,
  },
  {
    code: 'JUSTIFICACION_SALIDA',
    name: 'Justificación de salida',
    description: 'Justifica salidas en las fechas indicadas.',
    temporalMode: 'SINGLE_DATE',
    appointmentScope: 'ALL',
    isActive: true,
    sortOrder: 30,
  },
  {
    code: 'CUIDADOS_MATERNOS',
    name: 'Cuidados maternos',
    description: 'Registra cuidados maternos autorizados.',
    temporalMode: 'SINGLE_DATE',
    appointmentScope: 'ALL',
    isActive: true,
    sortOrder: 40,
  },
  {
    code: 'INCAPACIDAD',
    name: 'Incapacidad',
    description: 'Registra fechas amparadas por incapacidad.',
    temporalMode: 'DATE_RANGE',
    appointmentScope: 'ALL',
    isActive: true,
    sortOrder: 50,
  },
  {
    code: 'ONOMASTICO',
    name: 'Onomástico',
    description: 'Autoriza la incidencia por onomástico.',
    temporalMode: 'SINGLE_DATE',
    appointmentScope: 'BASE',
    isActive: true,
    sortOrder: 60,
  },
  {
    code: 'CONSTANCIA_TIEMPO_ISSSTE',
    name: 'Constancia de tiempo ISSSTE',
    description:
      'Registra fechas relacionadas con constancia de tiempo ISSSTE.',
    temporalMode: 'SINGLE_DATE',
    appointmentScope: 'ALL',
    isActive: true,
    sortOrder: 70,
  },
  {
    code: 'VACACIONES_PRIMER_PERIODO',
    name: 'Vacaciones primer periodo',
    description: 'Registra días usados del primer periodo vacacional.',
    temporalMode: 'MULTIPLE_DATES',
    appointmentScope: 'ALL',
    isActive: true,
    sortOrder: 80,
  },
  {
    code: 'VACACIONES_SEGUNDO_PERIODO',
    name: 'Vacaciones segundo periodo',
    description: 'Registra días usados del segundo periodo vacacional.',
    temporalMode: 'MULTIPLE_DATES',
    appointmentScope: 'ALL',
    isActive: true,
    sortOrder: 90,
  },
  {
    code: 'VACACIONES_ESTIMULOS',
    name: 'Vacaciones por estímulos',
    description: 'Registra días de vacaciones otorgados por estímulos.',
    temporalMode: 'MULTIPLE_DATES',
    appointmentScope: 'ALL',
    isActive: true,
    sortOrder: 100,
  },
  {
    code: 'COMISION',
    name: 'Comisión',
    description:
      'Registra fechas en que la persona trabajadora está en comisión.',
    temporalMode: 'DATE_RANGE',
    appointmentScope: 'ALL',
    isActive: true,
    sortOrder: 110,
  },
] as const;
